### ISSUE TITLE
serialized data in database

### ISSUE THREAD

**Issue by truth4oll** [baibaratsky/yii2-serialized-attributes-behavior#1]
Save serialized data in database through base64_encode, and get through base64_decode.
It helps avoid popular error with offset

**Comment by baibaratsky** [comment]
Hi! Could you provide more info on this error. I use this way to store serialized data for about 5 years without any problems.

**Comment by baibaratsky** [comment]
Oh, I think I know what you mean. The problem appears when you use non-UTF8 encoding in your database. Ok, I'll add this feature soon.

**Comment by truth4oll** [comment]
for example
http://php.net/manual/en/function.serialize.php#47509

**Comment by baibaratsky** [comment]
Your example is not about DB, it’s on submission of serialized data with HTML forms.
Here is more related one: http://www.jackreichert.com/2014/02/02/handling-a-php-unserialize-offset-error/

**Comment by baibaratsky** [comment]
As I said, there’s no problem when you use UTF8 in the DB.
