### ISSUE TITLE
You could add a Validator

### ISSUE THREAD

**Issue by robsch** [baibaratsky/yii2-serialized-attributes-behavior#5]
It would be nice if one could also specify a special rule four such fields. Now I have to use _safe_ for such fields. 

E.g.:

    public function rules() {
        return [
            [['my_field'], 'serialized', 'max' => 10000],
        ];
    }

With _max_ it could be checked that the string won't get truncated.

**Comment by baibaratsky** [comment]
Often you need to serialize an attribute not from the POST, so validation rules are not the place to configure serialization.
Also, I think it’s not  good idea to check length of serialized data using validation rules. These rules are for user‘s input validation, not for internal constraints checking.

**Comment by robsch** [comment]
Okay, I see and I think you're right.
